[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ukechords"
authors = [{name = "Jeremy Nickurak", email = "jeremy@nickurak.ca"}]
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]
dependencies = [
    "pychord==1.2.0",
    "pyxdg==0.28",
]


[project.urls]
Home = "https://nickurak.ca/ukechords/"

[project.scripts]
ident = "ukechords.ident:main"
