name: Ukechords test execution

on: [pull_request,push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: setup uv
        run: pip install uv
      - name: install ukechords
        run:  uv sync --dev --link-mode=symlink
      - name: Run flake8
        run: uv run flake8 src tests
      - name: Run pylint
        run: uv run pylint src tests
      - name: Run mypy
        run: uv run mypy --strict src tests
      - name: Run tests
        run: uv run pytest tests
